config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products do
    resources :comments, only: %i[edit create update destroy]
  end

  devise_for :users
  resources :order, only: %i[index show]
  resources :search, only: :index
  resources :cart, only: %i[index create update destroy]
  resources :webhooks, only: :create
  resources :checkout, only: [] do
    post :checkout_cart, on: :collection
    post :buy_now, on: :collection
    get :success, on: :collection
  end

  resources :attachements, only: %i[destroy]
  resources :home, only: %i[index show]
  resource :users, only: %i[show] do
    patch :update_role, on: :member
  end

  root to: 'home#index'
end

app/controllers/cart_controller.rb
# frozen_string_literal: true

class CartController < ApplicationController
  before_action :set_product, only: %i[create update destroy]
  skip_before_action :authenticate_user!
  before_action :authorize_user, only: %i[index update destroy]
  before_action :authorize_add_to_cart, only: %i[create]

  def index
    if @cart.present?
      flash[:notice] = 'Showing your cart'
    else
      flash[:alert] = 'Your cart is empty'
    end
  end

  def create
    if session[:cart] << set_product.id
      session[:quantity][set_product.id] = 1
      flash[:notice] = 'Product added to cart'
    else
      flash[:alert] = 'Product already in cart'
    end

    redirect_to cart_index_path
  end

  def update
    if (session[:quantity][set_product.id] = params[:quantity].to_i)
      flash[:notice] = 'Quantity updated'
    else
      flash[:alert] = 'Quantity not updated'
    end
    render :index
  end

  def destroy
    session[:quantity][set_product.id] = 0
    if session[:cart].delete(set_product.id)
      flash[:notice] = 'Product removed from cart'
    else
      flash[:alert] = 'Product not in cart'
    end
    redirect_to cart_index_path
  end

  private

  def authorize_user
    authorize session, policy_class: CartPolicy unless @cart.nil?
  end

  def authorize_add_to_cart
    authorize @set_product, policy_class: CartPolicy unless @set_product.nil?
  end

  def set_product
    @set_product ||= Product.find(params[:id])
  end
end

app/views/cart/_cart_index.html.erb
<% cart.each do |product| %>
  <%= render partial: 'cart/cart_product', locals: {product: product} %>
<% end %>
<% if cart.empty? %>
    <h2> Your cart is empty </h2>
  <% else %>

  <% cart_to_json(cart) %>
  Total Ammount: <%= cart_total(cart) %>$
  <% if user_signed_in? %>
    <%= button_to "Checkout", checkout_cart_checkout_index_path(cart),method: :post,remote: true,data: {disable_with: "Processing"}, class: 'btn btn-primary mt-auto mb-2', style: 'width:100%' %>
  <% else %>
    <%= button_to "Checkout", new_user_session_path,method: :get ,data: {disable_with: "Processing"}, class: 'btn btn-primary mt-auto mb-2', style: 'width:100%' %>
  <% end %>
<% end %>

app/views/cart/_cart_product.html.erb
<div class="card mb-3 post-card">
	<div class="card-body">
		<div class="row">
			<div class="col-md-2">
				<% if product.header_image.attached? %>
				<%= image_tag product.header_image, class: 'header-img' ,style: 'width:50%; height:auto;'%>
				<% end %>
			</div>
			<div class="col-md-8">
				<h5 class="card-title mb-2 text-dark"><%= product.title %></h5>
						Seller: <%= product.user.name %>
				<br>
						Price:<%= price(product) %>$
				<p class="text-secondary mb-0"><%= product.description %></p>
			</div>
		</div>
	</div>
	<div class="card-footer">
		<%= link_to 'Delete', cart_path(product), method: :delete, class: 'btn btn-danger mt-3 ml-5 mb-3', data: { confirm: "Are you sure you want to remove this product from cart?" } %>
		<div style="float: right;">
		<%= form_with(url: cart_url(product), method: :patch) do |f| %>
		<%= f.label :quantity, "Quantity" %>
		<%= f.select :quantity ,(1..product.quantity), {selected: session[:quantity][product.id]}, :onchange => "this.form.submit()" , class: 'form-control' %>
		<% end %>
		</div>
	</div>
</div>

app/views/cart/index.html.erb
<div class="ml-5 pl-5" >
<h1> Shopping Cart </h1>

<%= render partial: 'cart_index' , locals: { cart: @cart , total_amount: @total_amount } %>
</div>