config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products do
    resources :comments, only: %i[edit create update destroy]
  end

  devise_for :users
  resources :order, only: %i[index show]
  resources :search, only: :index
  resources :cart, only: %i[index create update destroy]
  resources :webhooks, only: :create
  resources :checkout, only: [] do
    post :checkout_cart, on: :collection
    post :buy_now, on: :collection
    get :success, on: :collection
  end

  resources :attachements, only: %i[destroy]
  resources :home, only: %i[index show]
  resource :users, only: %i[show] do
    patch :update_role, on: :member
  end

  root to: 'home#index'
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user
  validates :body, presence: true, length: { maximum: 1000 }
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_product
  before_action :set_comment, only: %i[edit update destroy]
  before_action :authorize_user, only: %i[edit update destroy]

  def edit; end

  def create
    @comment = @set_product.comments.new(comment_params)
    authorize @comment unless @comment.nil?
    @comment.user = current_user unless @comment.nil?
    if @comment.save
      flash[:notice] = 'Comment was successfully created.'
    else
      flash[:alert] = 'Comment was not created.'
    end
  end

  def update
    if @comment.update(comment_params)
      flash[:notice] = 'Comment was successfully updated.'
    else
      flash[:alert] = 'Comment was not updated.'
    end
  end

  def destroy
    if @comment.destroy
      flash[:notice] = 'Comment was successfully destroyed.'
    else
      flash[:alert] = 'Comment was not destroyed.'
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_product
    @set_product = Product.find(params[:product_id])
  end

  def authorize_user
    authorize @comment
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/views/comments/_comment.html.erb
<div class="comment-<%= comment.id %> container mb-5"
    style="border: 1px solid black; padding: 1em; margin: 1em;">
  <strong><%= comment.user.name %></strong><br />
  <% if (comment.updated_at - comment.created_at) > 1 %>
    <small>Edited <%= time_ago_in_words(comment.updated_at) %> ago</small>
  <% else %>
    <small>Created <%= time_ago_in_words(comment.created_at) %> ago</small>
  <% end %>

  <% if current_user == product.user or current_user == comment.user %>
    <div  class="btn-group float-right">
      <% if current_user == comment.user %>
        <div id="edit-btn-<%=comment.id%>">
          <%= link_to "Edit",edit_product_comment_path(product,comment) , remote: true, class:"btn btn-warning",id: "edit-button-#{comment.id}" %>
        </div>
      <% end %>

      <%= button_to "Delete", [product, comment],remote: true, class:"ml-2 btn btn-danger", method: :delete ,data: { confirm: "Are you sure you want to remove this comment?" }%>
    </div>

    <div id="edit-form-<%=comment.id%>" class="d-none pb-5 mb-5 ">
      <%= render 'comments/form',
        product: product,
        comment: comment,
        submit_label: "Update"%>
    </div>
  <% end %>

  <div id="comment-body-<%=comment.id%>">
    <%= comment.body %>
  </div>
</div>

app/views/comments/_comment_pane.html.erb
<div id="comment-pane">
  <% comments.each do |comment| %>
  <%= render partial: 'comments/comment', locals: {comment: comment ,product: product} %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<div id="comment-form">
    <%= form_with(model: [product, comment], remote: true, validate: true)  do |f| %>
        <%= f.text_area :body, class: "form-control"  %>
        <%= f.submit submit_label,class: "btn btn-primary  mt-1" %>
    <% end %>
</div>

app/views/comments/create.js.erb
$("#comment-form").val('');
$("#comment-pane").prepend("<%= j render 'comments/comment',product: @set_product,comment: @comment %>") <% unless @comment.nil? %>

app/views/comments/destroy.js.erb
$('.comment-<%=@comment.id%>').remove();

app/views/comments/edit.js.erb
$("#comment-body-<%=@comment.id%>").hide();
$("#edit-form-<%=@comment.id%>").removeClass("d-none")
$("#edit-btn-<%=@comment.id%>").hide();

app/views/comments/update.js.erb
$("#edit-btn-<%=@comment.id%>").show();
$("#edit-form-<%=@comment.id%>").addClass("d-none");
$("#comment-body-<%=@comment.id%>").show();
$("#comment-body-<%=@comment.id%>").load(location.href + " #comment-body-<%=@comment.id%>");