config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products do
    resources :comments, only: %i[edit create update destroy]
  end

  devise_for :users
  resources :order, only: %i[index show]
  resources :search, only: :index
  resources :cart, only: %i[index create update destroy]
  resources :webhooks, only: :create
  resources :checkout, only: [] do
    post :checkout_cart, on: :collection
    post :buy_now, on: :collection
    get :success, on: :collection
  end

  resources :attachements, only: %i[destroy]
  resources :home, only: %i[index show]
  resource :users, only: %i[show] do
    patch :update_role, on: :member
  end

  root to: 'home#index'
end

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<a class="navbar-brand">Ecommerece</a>
	<div class="collapse navbar-collapse" id="navbarNav">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item">
 				<%= link_to "Home", root_path,  class:'nav-link'%>
			</li>
    	<% if user_signed_in? %>
				<li class="nav-item">
					<%= link_to "My Profile",users_path(id: current_user.id),  class:'nav-link'%>
				</li>

				<% if current_user.Customer?  %>
				<li class="nav-item">
					<%= link_to "Cart" , cart_index_path, class:'nav-link'%>
				</li>

				<li class="nav-item">
					<%= link_to "Orders" , order_index_path, class:'nav-link'%>
				</li>

				<li class="nav-item">
					<%= link_to "Switch to Seller", update_role_users_path(id: current_user.id , role: "Seller"), method: :patch, validate: false , class:'nav-link'%>
				</li>

				<% elsif current_user.Seller?   %>
				<li class="nav-item">
					<%= link_to "My Products" ,products_path,  class:'nav-link'%>
				</li>

				<li class="nav-item">
					<%= link_to "Switch to Customer", update_role_users_path(id: current_user.id , role: "Customer"), method: :patch, validate: false , class:'nav-link'%>
				</li>

				<% elsif current_user.Admin? %>
				<li class="nav-item">
					<%= link_to "Dashboard" ,rails_admin_path,  class:'nav-link'%>
				</li>
				<% end %>
			<% else %>
			<li class="nav-item">
					<%= link_to "Sign In", new_user_session_path, class:'nav-link'%>
				</li>

				<li class="nav-item">
					<%= link_to "Sign Up", new_user_registration_path, class:'nav-link'%>
				</li>
			<% end %>
		</ul>
		<ul class="navbar-nav">
    	<% if user_signed_in? %>
				<li class="nav-item pt-2">
				<%= search_form_for(@query, url: search_index_path, method: :get) do |f| %>
				<%= f.search_field :title_or_description_i_cont, placeholder: "Search Products..." ,class: "form-control me-2" ,:onchange => "this.form.submit()"%>
			<% end %>

			</li>
				<li class="nav-item dropdown ml-3 ">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<%= image_tag(current_user.avatar,height: 30, width: 30 ,class: "rounded-circle") if current_user.avatar.present? %>
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
						<%= link_to "Edit Profile" ,edit_user_registration_path(current_user) , class:'dropdown-item'%>
						<%= link_to "Sign out", destroy_user_session_path, :method => :delete , class:'dropdown-item'%>
					</div>
      </li>
 			<% end %>
			<li class="nav-item pt-1">
				<%= link_to "About Us" ,home_path(1) , class:'nav-link'%>
			</li>
		</ul>
	</div>
</nav>

app/views/shared/_home_page.html.erb
<div class="row">
	<% products.each do |product| %>
    <div class="col-md-6 col-lg-4 mb-5 ">
      <div class="card post-card">
        <div class="header-image">
          <%= image_tag product.header_image, style: 'margin-left:18% ; width:60%;' if(product.header_image.attached?) %>
        </div>
        <div class="card-body d-flex flex-column">
          <h5 class="card-title"><%= product.title %></h5>
          <h6 class="text-secondary float-right">
            Seller:<%= product.user.name %>
            <br>
            Price:<%= product.price/100 %>$
          </h6>
          <p class="card-text">
            <%= truncate(product.description, length: 100) %>
          </p>
          <%= link_to "Product Details", product_path(product) ,class: 'btn btn-primary mt-auto mb-2' %>

          <% if valid_checkout_user(product)  %>
            <% if user_signed_in? %>
              <%= button_to "Buy Now", buy_now_checkout_index_path,params: {id: product.id},remote: true ,data: {disable_with: "Processing"},class: 'btn btn-primary mt-auto mb-2', style: 'width:100%' %>
            <% else %>
              <%= button_to "Buy Now", buy_now_checkout_index_path,params: {id: product.id},data: {disable_with: "Processing"},class: 'btn btn-primary mt-auto mb-2', style: 'width:100%' %>
            <% end %>
            <% if session[:cart].exclude?(product.id) %>
              <%= button_to "Add to Cart", cart_index_path,params: {id: product.id} ,remote: true ,data: {disable_with: "Adding to Cart"},class: 'btn btn-primary mt-auto mb-2' ,style: 'width:100%' %>
            <% else %>
              <%= button_to "Remove from Cart", cart_path(product.id),method: :delete,remote: true,data: {disable_with: "Removing from Cart"},class: 'btn btn-primary mt-auto mb-2' ,style: 'width:100%' %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
	<% end %>
</div>