config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products do
    resources :comments, only: %i[edit create update destroy]
  end

  devise_for :users
  resources :order, only: %i[index show]
  resources :search, only: :index
  resources :cart, only: %i[index create update destroy]
  resources :webhooks, only: :create
  resources :checkout, only: [] do
    post :checkout_cart, on: :collection
    post :buy_now, on: :collection
    get :success, on: :collection
  end

  resources :attachements, only: %i[destroy]
  resources :home, only: %i[index show]
  resource :users, only: %i[show] do
    patch :update_role, on: :member
  end

  root to: 'home#index'
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  include StripeProduct

  belongs_to :user
  has_one_attached :header_image
  has_many_attached :description_images
  has_many :comments, dependent: :destroy
  has_many :orderproducts, dependent: :destroy
  has_many :orders, through: :orderproducts, dependent: :destroy

  validates :header_image, :description_images,
            blob: { content_type: ['image/png', 'image/jpg', 'image/webp', 'image/jpeg'] }
  validates :title, presence: true, length: { minimum: 5, maximum: 20 }
  validates :description, presence: true, length: { minimum: 10, maximum: 200 }
  validates :price, presence: true, numericality: { greater_than: 0 }

  def serial_number
    format('PLN-%.6d', id)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show]
  before_action :set_product, only: %i[show edit update destroy]
  before_action :authorize_user, only: %i[show edit update destroy]

  def index
    @products = current_user.products
    authorize @products.first unless @products.empty?
    if @products.present?
      flash[:notice] = 'Showing your products'
    else
      flash[:alert] = 'You have no products'
    end
  end

  def show
    @comments = @set_product.comments.includes(:user).order(created_at: :desc)
    if @comments.present?
      flash[:notice] = 'Showing all comments and post'
    else
      flash[:alert] = 'no comments on post'
    end
  end

  def new
    @product = current_user.products.new
    authorize @product
  end

  def edit; end

  def create
    @product = current_user.products.new(product_params)
    authorize @product
    if @product.save
      flash[:notice] = 'Product was successfully created.'
      redirect_to edit_product_path(@product)
    else
      flash[:alert] = 'Product could not be created.'
    end
  end

  def update
    if @set_product.update(product_params)
      flash[:notice] = 'Product was successfully updated.'
      render :index
    else
      flash[:alert] = 'Product could not be updated.'

    end
  end

  def destroy
    if @set_product.destroy
      flash[:notice] = 'Product was successfully deleted.'
    else
      flash[:alert] = 'Product could not be deleted.'
    end
    redirect_to products_path
  end

  private

  def authorize_user
    authorize @set_product unless @set_product.nil?
  end

  def set_product
    @set_product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :quantity, :header_image, description_images: [])
  end
end

app/views/products/_couresel_images.html.erb
<% product.description_images.each do |image| %>
  <div class="carousel-item <%= couresal_first_image(image,product) %>",>
    <%= image_tag(image, class: 'd-block w-100',style: 'height: 50vh;') %>
  </div>
<% end %>

app/views/products/_edit.html.erb
<%= form_with model: product,validate: true do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, step: :any, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, class: 'form-control' %>
  </div>

  <div class="form-group" >
    <%= form.label :header_image %>
    <%= form.file_field :header_image , accept: 'image/jpeg,image/webp,image/png' %>
    <div class="mt-1">
      <% if product.header_image.attached? %>
        <small>Current image:</small>
        <%= image_tag(product.header_image, width: '10%') %>
        <%= link_to 'remove' , attachement_path(product.header_image.id), method: :delete %>
      <% end%>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :description_images %>
    <%= form.file_field :description_images, multiple: true , accept: 'image/jpeg,image/webp,image/png' %>
    <div class="mt-1">
      <% if product.description_images.attached? %>
        <small>Current images:</small>
        <% product.description_images.each do |image| %>
          <%= image_tag(image, width: '10%') %>
          <%= link_to 'remove' , attachement_path(image.id), method: :delete %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/products/_form.html.erb
<%= form_with model: product,validate: true do |form| %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, step: :any, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, class:'form-control' %>
  </div>

  <div class="form-group">
    <div class="mt-1 mb-1">
      <% if product.header_image.attached? %>
        <small>Current image:</small>
        <%= image_tag product.header_image, style: "width: 200px; display: block" %>
      <% end %>
    </div>
    <%= form.label :header_image %>
    <%= form.file_field :header_image, accept: 'image/jpeg,image/webp,image/png' %>
  </div>

  <div class="actions">
  <%= form.submit class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/products/_user_products_index.html.erb
<div class="ml-5 pl-5">
	<% products.each do |product|%>
		<%= link_to edit_product_path(product), class: 'text-decoration-none' do %>
		<div class="card mb-3 post-card">
			<div class="card-body">
				<div class="row">
					<div class="col-md-3">
						<% if product.header_image.attached? %>
						<%= image_tag product.header_image, class: 'header-img' %>
						<% end %>
					</div>
					<div class="col-md-8">
						<h5 class="card-title mb-2 text-dark"><%= product.title %></h5>
						Serial Number: <%= product.serial_number %>
						<p class="text-secondary mb-0"><%= product.description %></p>
					</div>
				</div>
			</div>
			<div class="card-footer">
				<%= link_to 'Delete', product_path(product), method: :delete, class: 'btn btn-danger mt-3 ml-5 mb-3', data: { confirm: "Are you sure?" } %>
			</div>
		</div>
		<% end %>
	<% end %>
</div>

app/views/products/edit.html.erb
<h2>Edit Your Product and add detailed images for the product</h2>
<%= render 'edit' , product: @set_product%>

app/views/products/index.html.erb
<h4 class='d-flex justify-content-between mb-4 ml-5 pl-5'>
  <span>All your Products</span>
  <%= link_to 'Add New Product', new_product_path, class: 'btn btn-primary' %>
</h4>

<%=render partial: 'user_products_index' ,locals: {products: @products}%>

app/views/products/new.html.erb
<h2>Create new product</h2>
<%= render 'form' , product: @product%>

app/views/products/show.html.erb
<div style='padding-left: 190px;'>
  <% if @set_product.description_images.present? %>
    <div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <%=render partial: 'couresel_images' ,locals: {product: @set_product}%>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  <% end %>

  <div style="padding-left:10px; margin-top:40px">
    <%= image_tag(@set_product.header_image,style: 'margin-right:2% ; width: 20%; float:right;')  if @set_product.header_image.attached?%>
    <h1 class="card-title mb-2"><%= @set_product.title %></h1>
    <h3 class="card-title mb-3">Owner: <%= @set_product.user.name %></h3>
    <p class="card-text mb-4">Description: <%= @set_product.description %></p>
    <p class="card-text mb-4">Price: <%= @set_product.price %></p>
    <p class="card-text mb-4">Available Quantity: <%= @set_product.quantity %></p>

    <% if valid_checkout_user(@set_product)  %>
      <% if user_signed_in? %>
        <%= button_to "Buy Now", buy_now_checkout_index_path,params: {id: @set_product.id},remote: true ,data: {disable_with: "Processing"},class: 'btn btn-primary mt-auto mb-2', style: 'width:100%' %>
      <% else %>
        <%= button_to "Buy Now", buy_now_checkout_index_path,params: {id: @set_product.id},data: {disable_with: "Processing"},class: 'btn btn-primary mt-auto mb-2', style: 'width:100%' %>
      <% end %>
      <% if session[:cart].exclude?(@set_product.id) %>
        <%= button_to "Add to Cart", cart_index_path,params: {id: @set_product.id} ,remote: true ,data: {disable_with: "Adding to Cart"},class: 'btn btn-primary mt-auto mb-2' ,style: 'width:100%' %>
      <% else %>
        <%= button_to "Remove from Cart", cart_path(@set_product.id),method: :delete,remote: true,data: {disable_with: "Removing from Cart"},class: 'btn btn-primary mt-auto mb-2' ,style: 'width:100%' %>
      <% end %>
    <% end %>
    </div>

  <div class="container" >
    <%= render partial: 'comments/comment_pane', locals: {comments: @comments ,product: @set_product} %>
    <% if user_signed_in? %>
    <%= render 'comments/form',product: @set_product,comment: @set_product.comments.new,submit_label: "Reply" %>
    <% end %>
  </div>
</div>